"""
NovaFlow Customer Success FTE — Channel Response Formatters
Adapts raw agent output to channel tone, length, and structure.
"""
from __future__ import annotations

MAX_LENGTHS = {
    "email":     2000,
    "whatsapp":  1600,   # Twilio hard limit; prefer 300
    "web_form":  1000,
}


def format_email(
    response: str,
    customer_name: str = "Valued Customer",
    ticket_id: str = "",
) -> str:
    name = customer_name.split()[0] if customer_name else "Valued Customer"
    return (
        f"Hi {name},\n\n"
        f"Thank you for reaching out to NovaFlow Support.\n\n"
        f"{response}\n\n"
        f"Please don't hesitate to reply if you have any further questions — "
        f"I'm happy to help.\n\n"
        f"Best regards,\n"
        f"NovaFlow Support Team\n"
        f"---\n"
        f"Ticket Reference: {ticket_id}\n"
        f"This response was generated by our AI assistant. "
        f"Reply to continue the conversation."
    )


def format_whatsapp(response: str) -> str:
    # Strip markdown for WhatsApp
    import re
    clean = re.sub(r"\*\*(.+?)\*\*", r"\1", response)
    clean = re.sub(r"\*(.+?)\*", r"\1", clean)
    clean = re.sub(r"#{1,6}\s", "", clean)

    if len(clean) > 300:
        clean = clean[:297] + "..."

    return f"{clean}\n\n📱 Reply for more help or type 'human' for live support."


def format_web_form(response: str, ticket_id: str = "") -> str:
    return (
        f"{response}\n\n"
        f"---\n"
        f"Need more help? Reply to this message or visit support.novasaas.io.\n"
        f"Ticket ref: {ticket_id}"
    )


def format_for_channel(
    response: str,
    channel: str,
    customer_name: str = "Valued Customer",
    ticket_id: str = "",
) -> str:
    if channel == "email":
        return format_email(response, customer_name, ticket_id)
    elif channel == "whatsapp":
        return format_whatsapp(response)
    else:
        return format_web_form(response, ticket_id)


def split_whatsapp_messages(text: str, max_len: int = 1600) -> list[str]:
    """Split long responses into WhatsApp-sized chunks."""
    if len(text) <= max_len:
        return [text]
    parts = []
    while text:
        if len(text) <= max_len:
            parts.append(text)
            break
        split_at = text.rfind(". ", 0, max_len)
        if split_at == -1:
            split_at = text.rfind(" ", 0, max_len)
        if split_at == -1:
            split_at = max_len
        parts.append(text[: split_at + 1].strip())
        text = text[split_at + 1 :].strip()
    return parts
